### ISSUE TITLE
As a user, I want links to websites when data is unable to be collected so that i always have dependable and relevant data.

### ISSUE THREAD

**Issue by aidanLarock** [Drov3r/COSC-4P02#46]

**Comment by JJMGula** [comment]
This issue was solved through the set up of live scraping using selenium, where a user will be returned a link to the proper information that isn't stored in our database. For example, we do not store player information in our database since that information became available to us after we implemented our original scraper and database classes. This was a perfect way to show the live scraping and return the specific URL of a player when asked about them.
